export const topBar = document.getElementById('top-bar')
export const exteriorImage = document.getElementById('exterior-image')
export const interiorImage = document.getElementById('interior-image')
export const exteriorColourSection = document.getElementById('exterior-buttons')
export const interiorColourSection = document.getElementById('interior-buttons')
export const wheelsButtonsSection = document.getElementById('wheel-buttons')
export const performanceBtn = document.getElementById('performance-btn')
export const fullSelfDrivingCheckbox = document.getElementById('full-self-driving-checkbox')
export const totalPriceElement = document.getElementById('total-price')
export const downPaymentElement = document.getElementById('down-payment')
export const monthlyPaymentElement = document.getElementById('monthly-payment')
export const accessoryCheckboxes = document.querySelectorAll('.accessory-form-checkbox')

